engine: Fix Cloe state machine
eclipse/cloe pull request #109
Opened 2022-09-21 08:31 UTC by fgguidi

Fix Cloe state machine for irregular situations to go through Abort and Disconnect.

2022-09-22 09:55 UTC, cassava commented
So I spent some time looking through the code in `simulation.cpp`, and I think that the proposed solution is an improvement, but will not be very much more informative than the previous state. For example, I'm not sure that we'll know which model caused the abort/reset/error.

2022-09-22 10:00 UTC, cassava requested changes
I made some suggestions on what the logged messages should say. I think this is more clear, since we can also catch errors in the states themselves and deal better with them there.

2022-09-26 08:47 UTC, fgguidi commented on engine/src/simulation.cpp
> +        logger()->critical("Aborting simulation due to error: {}", e.what());
I have pushed your suggestion.

2022-09-26 08:47 UTC, fgguidi commented on engine/src/simulation.cpp
> +        logger()->error("Resetting simulation due to error: {}", e.what());
I have pushed your suggestion.

2022-09-26 09:05 UTC, fgguidi commented
> I'm not sure that we'll know which model caused the abort/reset/error

2022-09-26 09:08 UTC, fgguidi commented
> So I spent some time looking through the code in `simulation.cpp`, and I think that the proposed solution is an improvement, but will not be very much more informative than the previous state. For example, I'm not sure that we'll know which model caused the abort/reset/error.

@cassava  If you would like to be more informative then we should print more information in the different implementations of foreach_model() functions in simulation_context.cpp. Right?

2022-09-26 10:06 UTC, cassava commented
> > So I spent some time looking through the code in `simulation.cpp`, and I think that the proposed solution is an improvement, but will not be very much more informative than the previous state. For example, I'm not sure that we'll know which model caused the abort/reset/error.
> 
> @cassava If you would like to be more informative then we should print more information in the different implementations of foreach_model() functions in simulation_context.cpp. Right?

Yes, that is correct. However, this was just an observation, I would just bear it in mind if we are dissatisfied with the output. Here I'd wait until we have actual examples. That can go in a separate PR.

2022-09-26 12:04 UTC, cassava approved these changes

2022-09-26 12:05 UTC, merged