[DRAFT] Support fusion components
eclipse/cloe pull request #17
Opened 2021-02-04 08:05 UTC by tobifalk

This PR extends the configuration of vehicle components. Previously, a single input (source) component was supported for each component, which is now extended to multiple input components of different derived type.

Resolves #9.

2021-02-18 17:12 UTC, cassava reviewed
> Reviewed 2 of 2 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/17)* status: 1 of 5 files reviewed, 8 unresolved discussions (waiting on @cassava and @tobifalk)

___
*[engine/CMakeLists.txt, line 59 at r1](https://reviewable.io/reviews/eclipse/cloe/17#-MTphamK2qt8GgMr4vmb:-MTphamL9ziBt1GMUi3T:b-uezuwv) ([raw file](https://github.com/eclipse/cloe/blob/b2e5c74aa8657f6d974f1756ed555ab4c8c80b9b/engine/CMakeLists.txt#L59)):*
> ```CMake
>         CONAN_PKG::boost
>         CONAN_PKG::cloe-models
>         CONAN_PKG::cloe-runtime
> ```

You probably don't need "cloe-runtime" because it's already in libstack. /pedantic
___
*[engine/src/simulation.cpp, line 81 at r2](https://reviewable.io/reviews/eclipse/cloe/17#-MTplbuE7b60zAHXHlw9:-MTplbuE7b60zAHXHlwA:b-ec5g0c) ([raw file](https://github.com/eclipse/cloe/blob/ad145833f4a7a023b5aac4a7d42f729eb13fbd22/engine/src/simulation.cpp#L81)):*
> ```cpp
> #include <fstream>  // for ofstream
> #include <future>   // for future<>, async
> #include <map>      // for map
> ```

`for map<>`
___
*[engine/src/simulation.cpp, line 489 at r2](https://reviewable.io/reviews/eclipse/cloe/17#-MTpmNno-a9oyLV1fTPZ:-MTpmNno-a9oyLV1fTP_:b-93mn6t) ([raw file](https://github.com/eclipse/cloe/blob/ad145833f4a7a023b5aac4a7d42f729eb13fbd22/engine/src/simulation.cpp#L489)):*
> ```cpp
>       }
>       // Get source components, if applicable.
>       if (!c.from.size()) {
> ```

I'd prefer it if integers aren't implicitely cast to bools. Use `c.from.size() == 0`
___
*[engine/src/stack.hpp, line 586 at r2](https://reviewable.io/reviews/eclipse/cloe/17#-MTpmltjB8sYEgrNWz9g:-MTpmltjB8sYEgrNWz9h:b-szfsb3) ([raw file](https://github.com/eclipse/cloe/blob/ad145833f4a7a023b5aac4a7d42f729eb13fbd22/engine/src/stack.hpp#L586)):*
> ```cpp
>   const std::string binding;
>   boost::optional<std::string> name;
>   boost::optional<std::string> from_tmp;
> ```

Delete from_tmp, and change `make_schema(&from_tmp` to `make_prototype<string>(...)`.
This means in `from_conf()` you just check if `c.has("from")` and if that's the case, then you set `from["component"] = `c.get<string>("from")`.
___
*[engine/src/stack_test.cpp, line 220 at r1](https://reviewable.io/reviews/eclipse/cloe/17#-MTphuIv1Vm9KltR-nUI:-MTphuIwEkHYejx5cYQT:b-kegfz0) ([raw file](https://github.com/eclipse/cloe/blob/b2e5c74aa8657f6d974f1756ed555ab4c8c80b9b/engine/src/stack_test.cpp#L220)):*
> ```cpp
>   uint64_t freq;
> 
>   Schema schema_impl() override {
> ```

You probably want to use "CONFABLE_SCHEMA(...)"
___
*[engine/src/stack_test.cpp, line 254 at r1](https://reviewable.io/reviews/eclipse/cloe/17#-MTpi_bl081NVOiWY4Xc:-MTpi_bl081NVOiWY4Xd:b-kxk10b) ([raw file](https://github.com/eclipse/cloe/blob/b2e5c74aa8657f6d974f1756ed555ab4c8c80b9b/engine/src/stack_test.cpp#L254)):*
> ```cpp
> 
> TEST(cloe_stack, deserialization_of_component) {
>   Json input = R"({        
> ```

Check your edit configuration for removing trailing whitespace.
___
*[engine/src/stack_test.cpp, line 301 at r1](https://reviewable.io/reviews/eclipse/cloe/17#-MTpl4EF7BmNCSg_XoXH:-MTpl4EF7BmNCSg_XoXI:b-3vlus5) ([raw file](https://github.com/eclipse/cloe/blob/b2e5c74aa8657f6d974f1756ed555ab4c8c80b9b/engine/src/stack_test.cpp#L301)):*
> ```cpp
>     std::shared_ptr<cloe::Component> from = std::shared_ptr<cloe::Component>{nullptr};
>     auto d = std::dynamic_pointer_cast<DummySensor>(std::shared_ptr<cloe::Component>(
>         std::move(cf->make(vc.components.find("cloe::default_world_sensor")->second.args, from))));
> ```

Not sure why this should work? Main reason, `find("cloe::default_world_sensor")` should not return anything, because no one put anything in vc.components...
___
*[engine/src/stack_test.cpp, line 304 at r1](https://reviewable.io/reviews/eclipse/cloe/17#-MTpieGw0G7juU6Iq607:-MTpieGw0G7juU6Iq608:bw67pre) ([raw file](https://github.com/eclipse/cloe/blob/b2e5c74aa8657f6d974f1756ed555ab4c8c80b9b/engine/src/stack_test.cpp#L304)):*
> ```cpp
>     ASSERT_EQ(d->get_freq(), 10);
>   }
> }
> ```

Missing newline -> check editor config for add end line / newline settings


<!-- Sent from Reviewable.io -->

2021-03-23 14:11 UTC, tobifalk reviewed
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/17)* status: 0 of 9 files reviewed, 8 unresolved discussions (waiting on @cassava)

___
*[engine/CMakeLists.txt, line 59 at r1](https://reviewable.io/reviews/eclipse/cloe/17#-MTphamK2qt8GgMr4vmb:-MWUPnnc-u883uhU0yga:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/b2e5c74aa8657f6d974f1756ed555ab4c8c80b9b/engine/CMakeLists.txt#L59)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

You probably don't need "cloe-runtime" because it's already in libstack. /pedantic
</blockquote></details>

Done.
___
*[engine/src/simulation.cpp, line 81 at r2](https://reviewable.io/reviews/eclipse/cloe/17#-MTplbuE7b60zAHXHlw9:-MWUPxSHE58yH8Y_rKMa:b-o1b8d0) ([raw file](https://github.com/eclipse/cloe/blob/ad145833f4a7a023b5aac4a7d42f729eb13fbd22/engine/src/simulation.cpp#L81)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

`for map<>`
</blockquote></details>

map<> was removed.
___
*[engine/src/simulation.cpp, line 489 at r2](https://reviewable.io/reviews/eclipse/cloe/17#-MTpmNno-a9oyLV1fTPZ:-MWUQ1ID27w7m7EE24lb:bt2vr1b) ([raw file](https://github.com/eclipse/cloe/blob/ad145833f4a7a023b5aac4a7d42f729eb13fbd22/engine/src/simulation.cpp#L489)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

I'd prefer it if integers aren't implicitely cast to bools. Use `c.from.size() == 0`
</blockquote></details>

Fixed.
___
*[engine/src/stack.hpp, line 586 at r2](https://reviewable.io/reviews/eclipse/cloe/17#-MTpmltjB8sYEgrNWz9g:-MWUQ45H3ZVtGUaKTLZ_:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/ad145833f4a7a023b5aac4a7d42f729eb13fbd22/engine/src/stack.hpp#L586)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Delete from_tmp, and change `make_schema(&from_tmp` to `make_prototype<string>(...)`.
This means in `from_conf()` you just check if `c.has("from")` and if that's the case, then you set `from["component"] = `c.get<string>("from")`.
</blockquote></details>

Done.
___
*[engine/src/stack_test.cpp, line 220 at r1](https://reviewable.io/reviews/eclipse/cloe/17#-MTphuIv1Vm9KltR-nUI:-MWUQAYU1pN62WGAGEKd:bt2vr1b) ([raw file](https://github.com/eclipse/cloe/blob/b2e5c74aa8657f6d974f1756ed555ab4c8c80b9b/engine/src/stack_test.cpp#L220)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

You probably want to use "CONFABLE_SCHEMA(...)"
</blockquote></details>

Fixed.
___
*[engine/src/stack_test.cpp, line 254 at r1](https://reviewable.io/reviews/eclipse/cloe/17#-MTpi_bl081NVOiWY4Xc:-MWUQDAG0Z2aGhAqqG4G:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/b2e5c74aa8657f6d974f1756ed555ab4c8c80b9b/engine/src/stack_test.cpp#L254)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Check your edit configuration for removing trailing whitespace.
</blockquote></details>

Done.
___
*[engine/src/stack_test.cpp, line 301 at r1](https://reviewable.io/reviews/eclipse/cloe/17#-MTpl4EF7BmNCSg_XoXH:-MWUQHSBBzD7lU8w3aCp:b-cqj59n) ([raw file](https://github.com/eclipse/cloe/blob/b2e5c74aa8657f6d974f1756ed555ab4c8c80b9b/engine/src/stack_test.cpp#L301)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Not sure why this should work? Main reason, `find("cloe::default_world_sensor")` should not return anything, because no one put anything in vc.components...
</blockquote></details>

This part was removed.
___
*[engine/src/stack_test.cpp, line 304 at r1](https://reviewable.io/reviews/eclipse/cloe/17#-MTpieGw0G7juU6Iq607:-MWUQEeA0sqKZ9bMfafH:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/b2e5c74aa8657f6d974f1756ed555ab4c8c80b9b/engine/src/stack_test.cpp#L304)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Missing newline -> check editor config for add end line / newline settings
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-26 09:12 UTC, cassava requested changes
> Reviewed 5 of 5 files at r3, 2 of 2 files at r4, 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/17)* status: 4 of 9 files reviewed, 3 unresolved discussions (waiting on @cassava, @clssn, and @tobifalk)

___
*[engine/src/stack_test.cpp, line 301 at r1](https://reviewable.io/reviews/eclipse/cloe/17#-MTpl4EF7BmNCSg_XoXH:-MWUSBx1CjuACRieUBZS:bo3orx5) ([raw file](https://github.com/eclipse/cloe/blob/b2e5c74aa8657f6d974f1756ed555ab4c8c80b9b/engine/src/stack_test.cpp#L301)):*
<details><summary><i>Previously, tobifalk (Tobias Falkenstein) wrote…</i></summary><blockquote>

This part was removed.
</blockquote></details>

Did you agree with my analysis, or did I miss something?
___
*[engine/src/stack_test.cpp, line 222 at r3](https://reviewable.io/reviews/eclipse/cloe/17#-MWURbkG1xrho4uEBBgw:-MWURbkG1xrho4uEBBgx:bvc3mdh) ([raw file](https://github.com/eclipse/cloe/blob/84d0fd09d5e5cb1a20a8f26e2da0b13d94148d2a/engine/src/stack_test.cpp#L222)):*
> ```cpp
> 
>   CONFABLE_SCHEMA(DummySensorConf) {
>     using namespace schema;  // NOLINT(build/namespaces)
> ```

This using not necessary.
___
*[engine/src/stack_test.cpp, line 270 at r3](https://reviewable.io/reviews/eclipse/cloe/17#-MWURuh35ahPlXQOXy5W:-MWURuh35ahPlXQOXy5X:b-fqjls0) ([raw file](https://github.com/eclipse/cloe/blob/84d0fd09d5e5cb1a20a8f26e2da0b13d94148d2a/engine/src/stack_test.cpp#L270)):*
> ```cpp
>     // Create a sensor component from the given configuration.
>     cc.from_conf(Conf{input});
>     // In production code, "some_obj_sensor" would be fetched from a list of all available sensors. Skip this step here.
> ```

This comment should be limited to column 80 for readability.


<!-- Sent from Reviewable.io -->

2021-03-26 09:37 UTC, cassava commented
___
*[engine/src/stack_test.cpp, line 229 at r5](https://reviewable.io/reviews/eclipse/cloe/17#-MWht4jqDKa57ilRLQuO:-MWht4jqDKa57ilRLQuP:b68loxf) ([raw file](https://github.com/eclipse/cloe/blob/8247a3035f204fc975811ffcb2441eb626f6e850/engine/src/stack_test.cpp#L229)):*
> ```cpp
>   }
> 
>   void to_json(Json& j) const override {
> ```

This to_json method not necessary, since it's provided by CONFABLE_SCHEMA.


<!-- Sent from Reviewable.io -->

2021-03-26 09:38 UTC, cassava commented
___
*[engine/src/stack_test.cpp, line 270 at r5](https://reviewable.io/reviews/eclipse/cloe/17#-MWhtLgA08bJ7pvKSVOz:-MWhtLgA08bJ7pvKSVP-:b-ay31bg) ([raw file](https://github.com/eclipse/cloe/blob/8247a3035f204fc975811ffcb2441eb626f6e850/engine/src/stack_test.cpp#L270)):*
> ```cpp
>     ComponentConf cc = ComponentConf("dummy_sensor", cf);
>     // Create a sensor component from the given configuration.
>     cc.from_conf(Conf{input});
> ```

We can use the fable/utility/gtest.hpp functions here, especially: `assert_from_conf`. We can supply it a raw string directly and it will do the right thing.


<!-- Sent from Reviewable.io -->

2021-03-26 09:40 UTC, cassava commented
___
*[engine/src/stack_test.cpp, line 344 at r5](https://reviewable.io/reviews/eclipse/cloe/17#-MWhtvh0Eew3Nki_YQKY:-MWhtvh1-_qxUL6m9zdh:buy9d5v) ([raw file](https://github.com/eclipse/cloe/blob/8247a3035f204fc975811ffcb2441eb626f6e850/engine/src/stack_test.cpp#L344)):*
> ```cpp
>     ComponentConf cc = ComponentConf("fusion_object_sensor", cf);
>     // Create a sensor component from the given configuration.
>     cc.from_conf(Conf{input});
> ```

See above comment on `assert_from_conf`.


<!-- Sent from Reviewable.io -->

2021-03-26 09:41 UTC, cassava commented
___
*[engine/src/stack_test.cpp, line 309 at r5](https://reviewable.io/reviews/eclipse/cloe/17#-MWhu8Ja0eST8zYooobz:-MWhu8Ja0eST8zYoooc-:bm17jte) ([raw file](https://github.com/eclipse/cloe/blob/8247a3035f204fc975811ffcb2441eb626f6e850/engine/src/stack_test.cpp#L309)):*
> ```cpp
>   for (auto& comp : comp_src) {
>     auto obj_s = std::dynamic_pointer_cast<ObjectSensor>(comp);
>     if (obj_s != NULL) {
> ```

Use `nullptr` instead of `NULL` in modern C++.


<!-- Sent from Reviewable.io -->

2021-03-26 09:41 UTC, cassava commented
___
*[engine/src/stack_test.cpp, line 314 at r5](https://reviewable.io/reviews/eclipse/cloe/17#-MWhuCpA6Y_q3BZs88tC:-MWhuCpA6Y_q3BZs88tD:bs4q9op) ([raw file](https://github.com/eclipse/cloe/blob/8247a3035f204fc975811ffcb2441eb626f6e850/engine/src/stack_test.cpp#L314)):*
> ```cpp
>     }
>     auto ego_s = std::dynamic_pointer_cast<EgoSensor>(comp);
>     if (ego_s != NULL) {
> ```

Ditto.


<!-- Sent from Reviewable.io -->

2021-03-26 09:44 UTC, cassava commented
___
*[models/src/cloe/component/lane_boundary.cpp, line 57 at r6](https://reviewable.io/reviews/eclipse/cloe/17#-MWhuefc8PjWH29ysDmg:-MWhuefc8PjWH29ysDmh:bo7f9gc) ([raw file](https://github.com/eclipse/cloe/blob/a682c69be8268d07fc5733ac95c882ef9d864845/models/src/cloe/component/lane_boundary.cpp#L57)):*
> ```cpp
>   return schema::Struct{
>       // clang-format off
>       {"id", make_schema(&id, "unique identifier in scene graph")},
> ```

This change doesn't hurt, but it also shouldn't be necessary. If it doesn't work, then perhaps we should solve it or create an issue so it's on our radar.


<!-- Sent from Reviewable.io -->

2021-03-26 13:17 UTC, clssn commented
___
*[models/src/cloe/component/lane_boundary.cpp, line 57 at r6](https://reviewable.io/reviews/eclipse/cloe/17#-MWhuefc8PjWH29ysDmg:-MWifbuT-gq4mSd88vn6:br9jpw6) ([raw file](https://github.com/eclipse/cloe/blob/a682c69be8268d07fc5733ac95c882ef9d864845/models/src/cloe/component/lane_boundary.cpp#L57)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

This change doesn't hurt, but it also shouldn't be necessary. If it doesn't work, then perhaps we should solve it or create an issue so it's on our radar.
</blockquote></details>

@cassava, care to elaborate on why this might not be working?


<!-- Sent from Reviewable.io -->

2021-04-08 09:28 UTC, tobifalk reviewed
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/17)* status: 1 of 9 files reviewed, 9 unresolved discussions (waiting on @cassava, @clssn, and @tobifalk)

___
*[engine/src/stack_test.cpp, line 222 at r3](https://reviewable.io/reviews/eclipse/cloe/17#-MWURbkG1xrho4uEBBgw:-MWy7HAWBc3Xgwyvdwwn:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/84d0fd09d5e5cb1a20a8f26e2da0b13d94148d2a/engine/src/stack_test.cpp#L222)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

This using not necessary.
</blockquote></details>

Done.
___
*[engine/src/stack_test.cpp, line 270 at r3](https://reviewable.io/reviews/eclipse/cloe/17#-MWURuh35ahPlXQOXy5W:-MXkEuH6-_GqmRyVEeWq:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/84d0fd09d5e5cb1a20a8f26e2da0b13d94148d2a/engine/src/stack_test.cpp#L270)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

This comment should be limited to column 80 for readability.
</blockquote></details>

Done.
___
*[engine/src/stack_test.cpp, line 229 at r5](https://reviewable.io/reviews/eclipse/cloe/17#-MWht4jqDKa57ilRLQuO:-MWy7PAwDxBto9xPNQRO:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/8247a3035f204fc975811ffcb2441eb626f6e850/engine/src/stack_test.cpp#L229)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

This to_json method not necessary, since it's provided by CONFABLE_SCHEMA.
</blockquote></details>

Done.
___
*[engine/src/stack_test.cpp, line 270 at r5](https://reviewable.io/reviews/eclipse/cloe/17#-MWhtLgA08bJ7pvKSVOz:-MXkIaeB45MZIeTdE3g9:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/8247a3035f204fc975811ffcb2441eb626f6e850/engine/src/stack_test.cpp#L270)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

We can use the fable/utility/gtest.hpp functions here, especially: `assert_from_conf`. We can supply it a raw string directly and it will do the right thing.
</blockquote></details>

Done.
___
*[engine/src/stack_test.cpp, line 309 at r5](https://reviewable.io/reviews/eclipse/cloe/17#-MWhu8Ja0eST8zYooobz:-MXkF4Dd798RtE4GKaAR:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/8247a3035f204fc975811ffcb2441eb626f6e850/engine/src/stack_test.cpp#L309)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Use `nullptr` instead of `NULL` in modern C++.
</blockquote></details>

Done.
___
*[engine/src/stack_test.cpp, line 314 at r5](https://reviewable.io/reviews/eclipse/cloe/17#-MWhuCpA6Y_q3BZs88tC:-MXkFJ4mBlNSsXzlIsVX:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/8247a3035f204fc975811ffcb2441eb626f6e850/engine/src/stack_test.cpp#L314)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[engine/src/stack_test.cpp, line 344 at r5](https://reviewable.io/reviews/eclipse/cloe/17#-MWhtvh0Eew3Nki_YQKY:-MXkIdG81qmE1nuij7ji:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/8247a3035f204fc975811ffcb2441eb626f6e850/engine/src/stack_test.cpp#L344)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

See above comment on `assert_from_conf`.
</blockquote></details>

Done.
___
*[models/src/cloe/component/lane_boundary.cpp, line 57 at r6](https://reviewable.io/reviews/eclipse/cloe/17#-MWhuefc8PjWH29ysDmg:-MXknUB7AifHuu2lPEMl:b-6cf8eg) ([raw file](https://github.com/eclipse/cloe/blob/a682c69be8268d07fc5733ac95c882ef9d864845/models/src/cloe/component/lane_boundary.cpp#L57)):*
<details><summary><i>Previously, clssn (Henning Claßen) wrote…</i></summary><blockquote>

@cassava, care to elaborate on why this might not be working?
</blockquote></details>

Ok, maybe the issue occurred for another reason. I was not able to reproduce it. Hence I removed the commit.


<!-- Sent from Reviewable.io -->

2021-04-14 08:48 UTC, cassava requested changes
Consider rebasing on master and running the pre-commit hook: `pre-commit run -s master -o HEAD` to get it to check all changes. Ignore the file-not-found error

> Reviewed 4 of 5 files at r5, 1 of 1 files at r6, 3 of 8 files at r7, 2 of 2 files at r8, 4 of 5 files at r9, 1 of 2 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/17#-:-MWhusAnCedcG8kq6WRR:bsu9ymk)* status: all files reviewed, 2 unresolved discussions (waiting on @tobifalk)

___
*[engine/src/simulation.cpp, line 489 at r9](https://reviewable.io/reviews/eclipse/cloe/17#-MYEDJi84xV7qhP8Hdh9:-MYEDJi84xV7qhP8HdhA:bmacf4) ([raw file](https://github.com/eclipse/cloe/blob/0b87aab65487f3ad3698ca9c2f6159456122897f/engine/src/simulation.cpp#L489)):*
> ```cpp
>       // Get input components, if applicable.
>       if (c.from.size() == 0) {
>         return nullptr;
> ```

This prevents components with 0 input components from being instantiated.
Better:

```
if (c.from.size() > 0) {
...
}
```
___
*[engine/src/simulation.cpp, line 494 at r9](https://reviewable.io/reviews/eclipse/cloe/17#-MYEETjOBdvEkzlSTEvx:-MYEETjOBdvEkzlSTEvy:b-dwknfr) ([raw file](https://github.com/eclipse/cloe/blob/0b87aab65487f3ad3698ca9c2f6159456122897f/engine/src/simulation.cpp#L494)):*
> ```cpp
>       for (const auto& from_comp_name : c.from) {
>         if (!v.has(from_comp_name)) {
>           continue;
> ```

Then here nullptr.


<!-- Sent from Reviewable.io -->

2021-04-14 08:49 UTC, cassava commented
I added a few fable library updates that you should review: a test file for CustomDeserializer, and a fix to the Array schema.

These commits should be rebased when you're done.





<!-- Sent from Reviewable.io -->

2021-04-14 10:21 UTC, tobifalk reviewed
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/17)* status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @cassava and @clssn)

___
*[engine/src/simulation.cpp, line 489 at r9](https://reviewable.io/reviews/eclipse/cloe/17#-MYEDJi84xV7qhP8Hdh9:-MYEt60w0W5N-b0THnS6:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/0b87aab65487f3ad3698ca9c2f6159456122897f/engine/src/simulation.cpp#L489)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

This prevents components with 0 input components from being instantiated.
Better:

```
if (c.from.size() > 0) {
...
}
```
</blockquote></details>

Done.
___
*[engine/src/simulation.cpp, line 494 at r9](https://reviewable.io/reviews/eclipse/cloe/17#-MYEETjOBdvEkzlSTEvx:-MYEt6r6DRZ5OSWbaKx7:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/0b87aab65487f3ad3698ca9c2f6159456122897f/engine/src/simulation.cpp#L494)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Then here nullptr.
</blockquote></details>

Done.
___
*[engine/src/stack_test.cpp, line 301 at r1](https://reviewable.io/reviews/eclipse/cloe/17#-MTpl4EF7BmNCSg_XoXH:-MYEt8Zf2htER7HJl-eF:bufdp5p) ([raw file](https://github.com/eclipse/cloe/blob/b2e5c74aa8657f6d974f1756ed555ab4c8c80b9b/engine/src/stack_test.cpp#L301)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Did you agree with my analysis, or did I miss something?
</blockquote></details>

As discussed, there was a mock-up vehicle configuration that you may have overlooked.


<!-- Sent from Reviewable.io -->

2021-04-21 08:00 UTC, cassava approved these changes
> Reviewed 1 of 1 files at r13, 3 of 4 files at r14, 1 of 1 files at r15, 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tobifalk)



<!-- Sent from Reviewable.io -->

2021-04-21 08:00 UTC, cassava commented
LGTM. You can rebase and merge.





<!-- Sent from Reviewable.io -->

2021-04-22 06:50 UTC, merged