Generate cloe/version.hpp header for cloe-runtime
eclipse/cloe pull request #197
Opened 2023-12-05 16:14 UTC by cassava

This allows users to support multiple Cloe runtime versions at compile-time.

This is generated from src/runtime/version.hpp.in
See the file for the documentation.

2023-12-07 15:26 UTC, clonker commented
see comments in #198 also there are conflicts apparently

2023-12-08 10:51 UTC, clonker requested changes

2023-12-08 10:52 UTC, cassava commented on runtime/CMakeLists.txt
> +# NOTE: The variable FABLE_VERSION is used throughout this CMakeLists file
Oops.

2023-12-08 10:57 UTC, clonker approved these changes

2023-12-08 10:59 UTC, merged