Stream json api data to a file
eclipse/cloe pull request #29
Opened 2021-05-03 12:37 UTC by tobifalk

A configuration option has been introduced that allows to write the same data that is already provided via Cloe's json api to a file. The web server does not need to be running in order to stream the data.

2021-06-24 14:46 UTC, cassava requested changes
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, 2 of 2 files at r4, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/29)* status: all files reviewed, 3 unresolved discussions (waiting on @clsim and @tobifalk)

___
*[engine/src/server.hpp, line 186 at r5](https://reviewable.io/reviews/eclipse/cloe/29#-McyTWWUDlS95-Q4saAv:-McyTWWV9qixKfkDQ02M:b-ubfqwb) ([raw file](https://github.com/eclipse/cloe/blob/60486ff01f73f99427d6fcea7b1f89492b514d2d/engine/src/server.hpp#L186)):*
> ```cpp
>   oak::BufferRegistrar buffer_api_registrar_{&server_, config.api_prefix, nullptr};
>   bool is_streaming_{false};
>   std::unique_ptr<cloe::utility::JsonFileSerializer> serializer_;
> ```

You will definitely want to add MsgPack or other compression ASAP, because there is a lot of duplicate stuff (like static endpoints).
___
*[engine/src/stack.hpp, line 430 at r5](https://reviewable.io/reviews/eclipse/cloe/29#-McyRaTc8oiz9RN1qJQl:-McyRaTc8oiz9RN1qJQm:bxf8oud) ([raw file](https://github.com/eclipse/cloe/blob/60486ff01f73f99427d6fcea7b1f89492b514d2d/engine/src/stack.hpp#L430)):*
> ```cpp
>               {"result", make_schema(&output_file_result, file_proto(), "file to store simulation result in")},
>               {"triggers", make_schema(&output_file_triggers, file_proto(), "file to store triggers in")},
>               {"data", make_schema(&output_file_data_stream, file_proto(), "file to store api data stream")},
> ```

We should use a more descriptive keyword here: api_contents / api_data / server_contents / endpoints_data / api_recording.

I think the term "recording" is useful, because it implies that the data changes over time and the whole set is there.

Make a suggestion ;-)
___
*[tests/bootstrap_vtd.json, line 6 at r5](https://reviewable.io/reviews/eclipse/cloe/29#-McyR-8u827F7e2V0GDy:-McyR-8u827F7e2V0GDz:bs2oepy) ([raw file](https://github.com/eclipse/cloe/blob/60486ff01f73f99427d6fcea7b1f89492b514d2d/tests/bootstrap_vtd.json#L6)):*
> ```JSON
>     "output": {
>       "files": {
>         "data": "data.json.gz"
> ```

I would put this in a separate test file and make sure you remove the data after the simulation runs through. Because otherwise you'll fill up your registry with data pretty quickly...


<!-- Sent from Reviewable.io -->

2021-06-25 08:57 UTC, tobifalk reviewed
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/29)* status: 12 of 20 files reviewed, 3 unresolved discussions (waiting on @cassava and @clsim)

___
*[engine/src/server.hpp, line 186 at r5](https://reviewable.io/reviews/eclipse/cloe/29#-McyTWWUDlS95-Q4saAv:-Md1NSDK0b-fN7rQ9Dnz:beoeduj) ([raw file](https://github.com/eclipse/cloe/blob/60486ff01f73f99427d6fcea7b1f89492b514d2d/engine/src/server.hpp#L186)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

You will definitely want to add MsgPack or other compression ASAP, because there is a lot of duplicate stuff (like static endpoints).
</blockquote></details>

Sure, that needs to follow soon.
___
*[engine/src/stack.hpp, line 430 at r5](https://reviewable.io/reviews/eclipse/cloe/29#-McyRaTc8oiz9RN1qJQl:-Md1NIneCSuheDydAvXx:bvyicl1) ([raw file](https://github.com/eclipse/cloe/blob/60486ff01f73f99427d6fcea7b1f89492b514d2d/engine/src/stack.hpp#L430)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

We should use a more descriptive keyword here: api_contents / api_data / server_contents / endpoints_data / api_recording.

I think the term "recording" is useful, because it implies that the data changes over time and the whole set is there.

Make a suggestion ;-)
</blockquote></details>

`"api_recording"` sounds good to me.
___
*[tests/bootstrap_vtd.json, line 6 at r5](https://reviewable.io/reviews/eclipse/cloe/29#-McyR-8u827F7e2V0GDy:-Md1NanPAIcs2tHeMjPv:bq7ljyn) ([raw file](https://github.com/eclipse/cloe/blob/60486ff01f73f99427d6fcea7b1f89492b514d2d/tests/bootstrap_vtd.json#L6)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

I would put this in a separate test file and make sure you remove the data after the simulation runs through. Because otherwise you'll fill up your registry with data pretty quickly...
</blockquote></details>

Now I am using /tmp as registry for that new test case.


<!-- Sent from Reviewable.io -->

2021-06-25 09:09 UTC, cassava requested changes
> Reviewed 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/29)* status: all files reviewed, 1 unresolved discussion (waiting on @clsim and @tobifalk)

___
*[tests/bootstrap_vtd.json, line 6 at r5](https://reviewable.io/reviews/eclipse/cloe/29#-McyR-8u827F7e2V0GDy:-Md1OfdABdeKDGSyfKym:btcnk1s) ([raw file](https://github.com/eclipse/cloe/blob/60486ff01f73f99427d6fcea7b1f89492b514d2d/tests/bootstrap_vtd.json#L6)):*
<details><summary><i>Previously, tobifalk (Tobias Falkenstein) wrote…</i></summary><blockquote>

Now I am using /tmp as registry for that new test case.
</blockquote></details>

Hmm. I see a flaw in our use of /tmp as a registry: /tmp is often a virtual filesystem directly on system memory. If a system doesn't reboot often, then /tmp may not be cleared for a long time. This is a surefire way to use up a system's memory.

Maybe do one or more of these things:
1. Remove the tmp registry after simulation (add a post_disconnect hook or make it part of BATS).
2. Move the tmp registry to a cache directory (~/.cache/cloe/tmp-registry).
3. Specify the simulation UUID so that we re-use an output directory instead of creating new ones.

I think our options are:
- 1 & 2
- 2 & 3

Since I don't know how large the api recording is, I think we should do step 2 in either case.


<!-- Sent from Reviewable.io -->

2021-06-25 13:16 UTC, clsim requested changes
> Reviewed 2 of 3 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, 1 of 2 files at r4, 2 of 6 files at r5, 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/29)* status: all files reviewed, 7 unresolved discussions (waiting on @tobifalk)

___
*[engine/src/simulation.hpp, line 74 at r6](https://reviewable.io/reviews/eclipse/cloe/29#-Md2Enx00OwJ0nU7FtDM:-Md2Enx00OwJ0nU7FtDN:b-8m6bgh) ([raw file](https://github.com/eclipse/cloe/blob/b23136441b27b9ff9eb883a58c6058d6ef24ec2d/engine/src/simulation.hpp#L74)):*
> ```cpp
>     return filepath;
>   }
> ```

No documentation?
___
*[oak/include/oak/registrar.hpp, line 160 at r6](https://reviewable.io/reviews/eclipse/cloe/29#-Md2FQ0Z-k7haOWwbrit:-Md2FQ0Z-k7haOWwbriu:bn4ttqx) ([raw file](https://github.com/eclipse/cloe/blob/b23136441b27b9ff9eb883a58c6058d6ef24ec2d/oak/include/oak/registrar.hpp#L160)):*
> ```cpp
>   void set_logger(Logger logger) { logger_ = logger; }
> 
>   std::vector<std::string> endpoints() const { return endpoints_; }
> ```

Returning a copy of a vector of strings is intended? - It is a quite expensive operation... 

How about return const std::vector<std::string>& ?
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 51 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1wjGw9JhAWixXTWL0:-Md1wjGw9JhAWixXTWL1:b6j9p0r) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L51)):*
> ```cpp
> 
>   explicit OutputStream(Logger& logger) : logger_(logger) {}
>   virtual ~OutputStream() noexcept = default;
> ```

OutputStream has no base clase and the d'tor is default which implicitly grants the noexcept property. For sake of bervity noexcept can be removed.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 67 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1ap5NDTaBG0Nx6qRu:-Md1ap5NDTaBG0Nx6qRv:bnc3sid) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L67)):*
> ```cpp
>              OutputStream* instance)
>       : write_function_(write_function), instance_(instance) {}
>   virtual ~Serializer() noexcept = default;
> ```

d'tor is noexcept by default.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 97 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1w209AKOVnpn6v_Fx:-Md1w209AKOVnpn6v_Fy:bnc3sid) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L97)):*
> ```cpp
>   using base = Serializer<TSerializerArgs...>;
>   using Serializer<TSerializerArgs...>::Serializer;
>   virtual ~AbstractJsonSerializer() noexcept = default;
> ```

d'tor is noexcept by default.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 110 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1w5T44e9bZ_iKpkot:-Md1w5T44e9bZ_iKpkou:bnc3sid) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L110)):*
> ```cpp
>   using base = Serializer<TSerializerArgs...>;
>   using Serializer<TSerializerArgs...>::Serializer;
>   virtual ~AbstractMsgPackSerializer() noexcept = default;
> ```

d'tor is noexcept by default.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 124 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1wtEFDva1E8Qwx1R0:-Md1wtEFDva1E8Qwx1R1:bnc3sid) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L124)):*
> ```cpp
>  public:
>   using OutputStream::OutputStream;
>   virtual ~BasicFileOutputStream() noexcept = default;
> ```

d'tor is noexcept by default.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 137 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1wzoi3DfpnbCjfM-o:-Md1wzoi3DfpnbCjfM-p:bnc3sid) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L137)):*
> ```cpp
>  public:
>   using BasicFileOutputStream::BasicFileOutputStream;
>   virtual ~FileOutputStream() noexcept = default;
> ```

d'tor is noexcept by default.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 147 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1x07c3pTvmMlqj11K:-Md1x07c3pTvmMlqj11L:bnc3sid) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L147)):*
> ```cpp
>   explicit FilteringOutputStream(Logger& logger)
>       : BasicFileOutputStream(logger), filter_(), out_(&filter_) {}
>   virtual ~FilteringOutputStream() noexcept = default;
> ```

d'tor is noexcept by default.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 163 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1x3APC2dsGzCylZ-g:-Md1x3APC2dsGzCylZ-h:bnc3sid) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L163)):*
> ```cpp
>  public:
>   using FilteringOutputStream::FilteringOutputStream;
>   virtual ~ZlibOutputStream() noexcept = default;
> ```

d'tor is noexcept by default.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 178 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1x4MdBzUDfrURckbR:-Md1x4MdBzUDfrURckbS:bnc3sid) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L178)):*
> ```cpp
>  public:
>   using FilteringOutputStream::FilteringOutputStream;
>   virtual ~GzipOutputStream() noexcept = default;
> ```

d'tor is noexcept by default.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 193 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1x4zG4dqgNDnowilm:-Md1x4zG4dqgNDnowiln:bnc3sid) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L193)):*
> ```cpp
>  public:
>   using FilteringOutputStream::FilteringOutputStream;
>   virtual ~Bzip2OutputStream() noexcept = default;
> ```

d'tor is noexcept by default.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 213 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1x69d9mjbqwljJ4Qk:-Md1x69d9mjbqwljJ4Ql:bnc3sid) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L213)):*
> ```cpp
>       , serializer_((void (OutputStream::*)(const char*, std::streamsize)) & TOutputStream::write,
>                     &outputstream_) {}
>   virtual ~FileSerializer() noexcept = default;
> ```

d'tor is noexcept by default.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 85 at r2](https://reviewable.io/reviews/eclipse/cloe/29#-Md20TXUA9JhjpCTT1V9:-Md20TXUA9JhjpCTT1VA:bn38w5) ([raw file](https://github.com/eclipse/cloe/blob/1f3f6c83d1d187af2e468fd569a35564cc776a56/runtime/include/cloe/utility/output_serializer.hpp#L85)):*
> ```cpp
> };
> 
> class AbstractJsonSerializerBase {
> ```

Since the whole JSON implementation moved into its own translation unit the AbstractJSONSerializerBase should also be moved there.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 92 at r2](https://reviewable.io/reviews/eclipse/cloe/29#-Md25-Kf4XwFoqjh0dTc:-Md25-Kf4XwFoqjh0dTd:bmyytsk) ([raw file](https://github.com/eclipse/cloe/blob/1f3f6c83d1d187af2e468fd569a35564cc776a56/runtime/include/cloe/utility/output_serializer.hpp#L92)):*
> ```cpp
> 
> template <typename... TSerializerArgs>
> class AbstractJsonSerializer : public Serializer<TSerializerArgs...>,
> ```

Since the whole JSON implementation moved into its own translation unit the AbstractJSONSerializer should also be moved there.
___
*[runtime/include/cloe/utility/output_ser [...]

2021-06-28 07:38 UTC, cassava reviewed
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/29)* status: 16 of 20 files reviewed, 7 unresolved discussions (waiting on @cassava, @clsim, and @tobifalk)

___
*[oak/include/oak/registrar.hpp, line 160 at r6](https://reviewable.io/reviews/eclipse/cloe/29#-Md2FQ0Z-k7haOWwbrit:-MdGXiX0CkDDvYweOOKE:b-pbdqz3) ([raw file](https://github.com/eclipse/cloe/blob/b23136441b27b9ff9eb883a58c6058d6ef24ec2d/oak/include/oak/registrar.hpp#L160)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

Returning a copy of a vector of strings is intended? - It is a quite expensive operation... 

How about return const std::vector<std::string>& ?
</blockquote></details>

Agreed.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 51 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1wjGw9JhAWixXTWL0:-MdGXmI518cJ3LuP8lvt:b-itmzu0) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L51)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

OutputStream has no base clase and the d'tor is default which implicitly grants the noexcept property. For sake of bervity noexcept can be removed.
</blockquote></details>

Agreed. We're not using`noexcept` consistently enough for it to make sense to add it here. I like this answer here: https://stackoverflow.com/questions/10787766/when-should-i-really-use-noexcept
___
*[runtime/include/cloe/utility/output_serializer_json.hpp, line 34 at r6](https://reviewable.io/reviews/eclipse/cloe/29#-Md22joT-rzahVqSET6V:-MdGYNv4BD-WOR_yil32:b-pbdqz3) ([raw file](https://github.com/eclipse/cloe/blob/b23136441b27b9ff9eb883a58c6058d6ef24ec2d/runtime/include/cloe/utility/output_serializer_json.hpp#L34)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

Suggestion: Use 'enum class' instead of 'enum' for sake of type-safety.
</blockquote></details>

Agreed.


<!-- Sent from Reviewable.io -->

2021-06-28 16:03 UTC, tobifalk reviewed
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/29)* status: 10 of 27 files reviewed, 6 unresolved discussions (waiting on @cassava, @clsim, and @tobifalk)

___
*[engine/src/simulation.hpp, line 74 at r6](https://reviewable.io/reviews/eclipse/cloe/29#-Md2Enx00OwJ0nU7FtDM:-MdIIrSGDX1tRZ0b59mT:b-jlmowy) ([raw file](https://github.com/eclipse/cloe/blob/b23136441b27b9ff9eb883a58c6058d6ef24ec2d/engine/src/simulation.hpp#L74)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

No documentation?
</blockquote></details>

Doc added, thanks.
___
*[oak/include/oak/registrar.hpp, line 160 at r6](https://reviewable.io/reviews/eclipse/cloe/29#-Md2FQ0Z-k7haOWwbrit:-MdGFjUQ1L8RHVhX6xCF:bt2vr1b) ([raw file](https://github.com/eclipse/cloe/blob/b23136441b27b9ff9eb883a58c6058d6ef24ec2d/oak/include/oak/registrar.hpp#L160)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

Returning a copy of a vector of strings is intended? - It is a quite expensive operation... 

How about return const std::vector<std::string>& ?
</blockquote></details>

Fixed.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 67 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1ap5NDTaBG0Nx6qRu:-MdIJ7Dm8VRdbImAuPWG:bt2vr1b) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L67)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

d'tor is noexcept by default.
</blockquote></details>

Fixed.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 97 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1w209AKOVnpn6v_Fx:-MdIJFLf5sx1xCuhTxfn:bt2vr1b) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L97)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

d'tor is noexcept by default.
</blockquote></details>

Fixed.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 110 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1w5T44e9bZ_iKpkot:-MdIJK-VCdbilE0ddZOP:bt2vr1b) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L110)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

d'tor is noexcept by default.
</blockquote></details>

Fixed.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 124 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1wtEFDva1E8Qwx1R0:-MdIJU4Q4h8O25F55tbm:bt2vr1b) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L124)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

d'tor is noexcept by default.
</blockquote></details>

Fixed.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 137 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1wzoi3DfpnbCjfM-o:-MdIJXtk4EGOfZ2BIQ_Z:bt2vr1b) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L137)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

d'tor is noexcept by default.
</blockquote></details>

Fixed.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 147 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1x07c3pTvmMlqj11K:-MdIJqTK-Fwi9vcQ5yVa:bt2vr1b) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L147)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

d'tor is noexcept by default.
</blockquote></details>

Fixed.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 163 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1x3APC2dsGzCylZ-g:-MdIJvcPEGXidhdtzMkB:bt2vr1b) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L163)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

d'tor is noexcept by default.
</blockquote></details>

Fixed.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 178 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1x4MdBzUDfrURckbR:-MdIKB2w-YBRGan2p8kB:bt2vr1b) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L178)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

d'tor is noexcept by default.
</blockquote></details>

Fixed.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 193 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1x4zG4dqgNDnowilm:-MdILrmK6Av9EfkVpRKC:bt2vr1b) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L193)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

d'tor is noexcept by default.
</blockquote></details>

Fixed.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 213 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1x69d9mjbqwljJ4Qk:-MdILwNv88ZR-q2qxC6d:bt2vr1b) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L213)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

d'tor is noexcept by default.
</blockquote></details>

Fixed.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 85 at r2](https://reviewable.io/reviews/eclipse/cloe/29#-Md20TXUA9JhjpCTT1V9:-MdIJ8pW2-0NIOqtfevR:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/1f3f6c83d1d187af2e468fd569a35564cc776a56/runtime/include/cloe/utility/output_serializer.hpp#L85)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

Since the whole JSON implementation moved into its own translation unit the AbstractJSONSerializerBase should also be moved there.
</blockquote></details>

Done.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 92 at r2](https://reviewable.io/reviews/eclipse/cloe/29#-Md25-Kf4XwFoqjh0dTc:-MdIJAZt7V2iwYNXK7x1:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/1f3f6c83d1d187af2e468fd569a35564cc776a56/runtime/include/cloe/utility/output_serializer.hpp#L92)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

Since the whole JSON implementation moved into its own translation unit the AbstractJSONSerializer should also be moved there.
</blockquote></details>

Done.
___
*[runtime/include/cloe/utility/output_serializer.hpp, line 106 at r2](https://reviewable.io/reviews/eclipse/cloe/29#-Md253-8EZJ67vs9mTVy:-MdIJGhW52gkpCcJ2Obx:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/1f3f6c83d1d187af2e468fd569a35564cc776a56/runtime/include/cloe/utility/output_serializer.hpp#L106)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

Since the whole JSON implementation moved into its own translation unit and apparently the MessagePack Output was removed the AbstractMessagepackSerializer could be removed also (or moved into its own translation unit like the JSON one)
</blockquote></details>

Done.
___
*[runtime/include/cloe/utility/output_serializer_json.hpp, line 34 at r6](https://reviewable.io/reviews/eclipse/cloe/29#-Md22joT-rzahVqSET6V:-MdILy117LaJPRcA9tdA:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/b23136441b27b9ff9eb883a58c6058d6e [...]

2021-06-29 08:09 UTC, clsim approved these changes
> Reviewed 2 of 2 files at r7, 1 of 1 files at r8, 6 of 6 files at r9, 1 of 1 files at r10, 3 of 5 files at r11, 6 of 6 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/29)* status: all files reviewed, 1 unresolved discussion (waiting on @cassava)

___
*[runtime/include/cloe/utility/output_serializer.hpp, line 51 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1wjGw9JhAWixXTWL0:-MdLdyNY2CCdU1di9dG6:b-xv4haa) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L51)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Agreed. We're not using`noexcept` consistently enough for it to make sense to add it here. I like this answer here: https://stackoverflow.com/questions/10787766/when-should-i-really-use-noexcept
</blockquote></details>

Frankly, I am not sure whether inconsistency is a good reason against a good measure. For instance I would not intentionally stop trying to be polite, just because I am (unintentionally) not always sufficiently polite. 

But my point is redundancy & the lack of a use-case:
#1: The specification determines that this function is noexcept.
#2: Usual compilers flag all ctors/dtors implicitly as noexcept*. 
#3: What for?**

*) Experiment A:
Throw from a dtor while being guarded with a try-catch block. std:terminate will be called anyhow, for violating the (implicit) noexcept guarantee.
For instance the gcc 7.5 drops an explicit warning at compile time. Assuming -Werror the user would have to stop throwing or explicitly declare noexcept(false).

**)
Answer #1 https://stackoverflow.com/a/10788136 says
"It seems like the biggest optimization gains are from user optimizations, not compiler ones due to the possibility of checking noexcept and overloading on it." The point here is, that we neither do Template-Metaprogramming based on the noexcept operator, nor does a missing noexcept attribute necesarily influence the result of the noexcept operator.
Answer #2 stresses the point of clear semantics. Which is obvious for a default implementation.

I.e. the central point is pretty vague for a non-high-performance application.


<!-- Sent from Reviewable.io -->

2021-06-29 08:09 UTC, clsim approved these changes
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/29)* status: all files reviewed, 1 unresolved discussion (waiting on @cassava)



<!-- Sent from Reviewable.io -->

2021-06-30 08:06 UTC, cassava requested changes
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/29)* status: all files reviewed, 3 unresolved discussions (waiting on @tobifalk)

___
*[runtime/include/cloe/utility/output_serializer.hpp, line 51 at r1](https://reviewable.io/reviews/eclipse/cloe/29#-Md1wjGw9JhAWixXTWL0:-MdM8kWn-OCHk8KFaMbf:b-m3txv9) ([raw file](https://github.com/eclipse/cloe/blob/a02f804a74c82f1387fdf81b8fac3fa977722d42/runtime/include/cloe/utility/output_serializer.hpp#L51)):*
<details><summary><i>Previously, clsim (Martin Henselmeyer) wrote…</i></summary><blockquote>

Frankly, I am not sure whether inconsistency is a good reason against a good measure. For instance I would not intentionally stop trying to be polite, just because I am (unintentionally) not always sufficiently polite. 

But my point is redundancy & the lack of a use-case:
#1: The specification determines that this function is noexcept.
#2: Usual compilers flag all ctors/dtors implicitly as noexcept*. 
#3: What for?**

*) Experiment A:
Throw from a dtor while being guarded with a try-catch block. std:terminate will be called anyhow, for violating the (implicit) noexcept guarantee.
For instance the gcc 7.5 drops an explicit warning at compile time. Assuming -Werror the user would have to stop throwing or explicitly declare noexcept(false).

**)
Answer #1 https://stackoverflow.com/a/10788136 says
"It seems like the biggest optimization gains are from user optimizations, not compiler ones due to the possibility of checking noexcept and overloading on it." The point here is, that we neither do Template-Metaprogramming based on the noexcept operator, nor does a missing noexcept attribute necesarily influence the result of the noexcept operator.
Answer #2 stresses the point of clear semantics. Which is obvious for a default implementation.

I.e. the central point is pretty vague for a non-high-performance application.

</blockquote></details>

For me, consistency has a lot to do with understandability and readability. But your points are all valid of course.
___
*[tests/test_vtd.bats, line 22 at r7](https://reviewable.io/reviews/eclipse/cloe/29#-MdQwxhqAefUpckUXhy6:-MdQwxhqAefUpckUXhy7:b-o0uxfe) ([raw file](https://github.com/eclipse/cloe/blob/c9a3d2f079ac211111f8652f48d49f188a8d7c17/tests/test_vtd.bats#L22)):*
> ```Shell
>     fi
>     # Remove the temporary registry.
>     rm -rf "$cloe_tmp_registry"
> ```

Let's not use `-f` since that's dangerous, but ignore failure to remove with `|| true`.
___
*[tests/test_vtd.bats, line 40 at r7](https://reviewable.io/reviews/eclipse/cloe/29#-MdQx6mF1j18FCs1mxsk:-MdQx6mF1j18FCs1mxsl:bs4q9op) ([raw file](https://github.com/eclipse/cloe/blob/c9a3d2f079ac211111f8652f48d49f188a8d7c17/tests/test_vtd.bats#L40)):*
> ```Shell
>     cloe_engine_with_tmp_registry run test_vtd_api_recording.json
>     # Remove the test registry.
>     rm -rf "$cloe_tmp_registry"
> ```

Ditto.
___
*[tests/bootstrap_vtd.json, line 6 at r5](https://reviewable.io/reviews/eclipse/cloe/29#-McyR-8u827F7e2V0GDy:-MdQx9RPAkC8-rtoGGTl:b-ucfknh) ([raw file](https://github.com/eclipse/cloe/blob/60486ff01f73f99427d6fcea7b1f89492b514d2d/tests/bootstrap_vtd.json#L6)):*
<details><summary><i>Previously, tobifalk (Tobias Falkenstein) wrote…</i></summary><blockquote>

Done (1&2).
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2021-06-30 09:05 UTC, tobifalk reviewed
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/29)* status: all files reviewed, 3 unresolved discussions (waiting on @cassava and @tobifalk)

___
*[tests/test_vtd.bats, line 22 at r7](https://reviewable.io/reviews/eclipse/cloe/29#-MdQwxhqAefUpckUXhy6:-MdR9aShDI6yKl8p56pD:bt2vr1b) ([raw file](https://github.com/eclipse/cloe/blob/c9a3d2f079ac211111f8652f48d49f188a8d7c17/tests/test_vtd.bats#L22)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Let's not use `-f` since that's dangerous, but ignore failure to remove with `|| true`.
</blockquote></details>

Fixed.
___
*[tests/test_vtd.bats, line 40 at r7](https://reviewable.io/reviews/eclipse/cloe/29#-MdQx6mF1j18FCs1mxsk:-MdR9cKVC2za_oSjXGYA:bt2vr1b) ([raw file](https://github.com/eclipse/cloe/blob/c9a3d2f079ac211111f8652f48d49f188a8d7c17/tests/test_vtd.bats#L40)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-06-30 10:06 UTC, cassava approved these changes
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/29)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @cassava and @clsim)



<!-- Sent from Reviewable.io -->

2021-06-30 10:07 UTC, merged