Improve Conan version overriding
eclipse/cloe pull request #5
Opened 2021-01-15 16:14 UTC by cassava

This PR does a few things:

1. It makes it easier to override *boost* by being less specific on which versions we need.
2. Refacotr `Makefile.all` and `Makefile.package` to let Conan build the requirements by default.

This changes the way we build cloe by default a little, but I think it's for the better:

Before, it would look like something like this:
```bash
make VENDOR_ONLY=1 export
make export
make -f Makefile.package package
```

After this PR:
```bash
make export-vendor export package
```

2021-01-20 13:09 UTC, cassava commented
Unfortunately, the Conan Center has such bad performance that using version ranges is leading to timeouts.

```console
$ mkdir -p build
$ conan install . --install-folder=build --build=missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/conans/search?q=boost%2F%2A&ignorecase=False (Caused by ReadTimeoutError("HTTPSConnectionPool(host='conan.bintray.com', port=443): Read timed out. (read timeout=60.0)"))

Unable to connect to conan-center=https://conan.bintray.com
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
make: *** [../Makefile.package:226: build/conanbuildinfo.cmake] Error 1
```

2021-01-20 13:21 UTC, cassava commented
Setting `request_timeout = 360` in `~/.conan/conan.conf` will resolve this problem.

- [ ] Document this issue.
- [ ] Document workaround A: changing `request_timeout`
- [ ] Document workaround B: using another/private repository

2021-01-20 15:57 UTC, tobifalk requested changes
- [ ] Update the build section in `Readme.md`.
- [ ] Fix target description in Makefile.all (s. comment).

The local builds that I tested all worked fine.
For the docker build, I had to follow your suggestion and add `conan config set general.request_timeout=360` to the Dockerfile.
`$ make ubuntu-18.04`
```
...
 boost/1.69.0: Downloaded recipe revision 0
 WARN: fable/1.0.0@cloe/develop: requirement boost/[>=1.65.1] overridden by cloe-runtime/0.18.0-nightly-tmp@cloe/develop to boost/1.75.0 
 WARN: fable/1.0.0@cloe/develop: requirement boost/[>=1.65.1] overridden by cloe-runtime/0.18.0-nightly-tmp@cloe/develop to boost/1.75.0 
 ERROR: Conflict in cpp-netlib/0.13.0@cloe/stable:
     'cpp-netlib/0.13.0@cloe/stable' requires 'boost/1.69.0' while 'cloe-models/0.18.0-nightly-tmp@cloe/develop' requires 'boost/1.75.0'.
     To fix this conflict you need to override the package 'boost' in your root package.
 ```

2021-01-25 12:34 UTC, cassava commented on Makefile.all
> +$(call make_cloe_target, package-outdated,     "create cloe package and dependencies [conan-cache]")
Fixed.

2021-01-25 16:28 UTC, tobifalk approved these changes
LGTM!

2021-01-25 17:40 UTC, clssn approved these changes
Great job! I especially appreciate the `export-vendor` target since for common things the user shouldn't have to apply "advanced" syntax of using variables as before in `make VENDOR_ONLY=1 export`.

2021-01-25 17:41 UTC, merged